//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncludeSpec.EntityFramework.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.ChildGroups = new HashSet<Group>();
            this.Users = new HashSet<User>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentGroupId { get; set; }
    
        public virtual ICollection<Group> ChildGroups { get; set; }
        public virtual Group ParentGroup { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
